### ISSUE TITLE
getting it working with Delugevpn and prometheus with Docker compose

### ISSUE THREAD

**Issue by rjdodd00** [tobbez/deluge_exporter#10]
Question out of curiosity, has this been test or worked with the above.

I have been trying to get it all working but I keep getting errors like 

 `  File "/usr/local/lib/python3.9/ssl.py", line 1329, in _real_connect
    super().connect(addr)
socket.gaierror: [Errno -2] Name does not resolve `

**Comment by tobbez** [comment]
It has not been tested, but should likely work (as long as the deluge RPC port is exposed so the exporter can connect to it).

The excerpt of the traceback you provided indicates that you passed a hostname that cannot be resolved in the container. You could try fixing your name resolution or passing the IP address instead.

Closing this issue as it doesn't seem to be a problem with deluge_exporter itself.
