### ISSUE TITLE
deluge connecting information

### ISSUE THREAD

**Issue by sinicide** [tobbez/deluge_exporter#15]
Wanted to leave a note about the User you need to connect with as I ran into an issue using a user of Normal Level `5` I needed to connect with a user of Admin Level `10` according to https://dev.deluge-torrent.org/wiki/UserGuide/Authentication when connecting with a Normal user, I did not see any errors in exporter logs, but metrics reported as 0. Once I connected with an Admin Level user, I was able to get metrics.

Anyhow great project, thanks for the hard work!

**Comment by tobbez** [comment]
Normal users can only see information for torrents they themselves added to a deluge instance, while administrators can see information for all torrents in the instance.

This means the account used for the exporter has to be either:

- the same account you use when using deluge normally, or
- an admin account

In short: if an account can see the torrents when connecting using the deluge client, then metrics for those torrents will be reported when using that account in the exporter.

Note that this only applies for the torrent count metrics (`deluge_torrents`, `deluge_torrents_by_label`). All other metrics are tracked globally for an instance and are available regardless of authentication level.
