### ISSUE TITLE
socket.gaierror: [Errno -2] Name does not resolve

### ISSUE THREAD

**Issue by travnewmatic** [tobbez/deluge_exporter#18]
was working

now its not :)

my deluge does still appear to be listening and responding on the usual daemon port, and my auth creds haven't changed

i can log in from my desktop client to the daemon port successfully

but deluge-exporter isn't having it:

```
2022-04-12 15:06:56.388 | ERROR    | __main__:<module>:202 - An error has been caught in function '<module>', process 'MainProcess' (1), thread 'MainThread' (139796222131016):
Traceback (most recent call last):
> File "/deluge_exporter.py", line 202, in <module>
    start_exporter()
  File "/deluge_exporter.py", line 187, in start_exporter
    start_http_server(port, address)
  File "/usr/local/lib/python3.10/site-packages/prometheus_client/exposition.py", line 168, in start_wsgi_server
    TmpServer.address_family, addr = _get_best_family(addr, port)
  File "/usr/local/lib/python3.10/site-packages/prometheus_client/exposition.py", line 157, in _get_best_family
    infos = socket.getaddrinfo(address, port)
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve
```

i see your image on docker hub was updated 9 hours ago, and that seems to be in line with when my issues started (i've been starting and stopping kubernetes nodes, so your image would have been pulled recently)

please let me know what other information i can provide.  love your project!

not sure if it helps but this is the exact image i'm running:
`docker.io/tobbez/deluge_exporter@sha256:a6df565530449d3a0ecedab7f6dd329f68712c2934d6672471f6a5cebce56918`

**Comment by ahurtaud** [comment]
I am pretty sure it is because of some sort of new base image : https://github.com/tobbez/deluge_exporter/commit/34e4e120e7fdd177bcf4000e1daaa24996858756

unfortunately I cannot even revert to an old image as even older tags have been overwritten and have the same issue :(

**Comment by lavrentivs** [comment]
[This](https://github.com/tobbez/deluge_exporter/blob/27cb9e50e4052301ae1ed2d1a7f424719c1daa5e/deluge_exporter.py#L199) "" for listening address seems to be the issue. Replacing it with "0.0.0.0" fixed it for me. If you don't want to bother with rebuilding the image, you can simply add `LISTEN_ADDRESS=0.0.0.0` as an env variable.

**Comment by travnewmatic** [comment]
thanks @lavrentivs that did it!  have a great weekend!
