### ISSUE TITLE
Deluge 2 support

### ISSUE THREAD

**Issue by brandond** [tobbez/deluge_exporter#2]
Deluge 2 has been out for a while; are you planning on adding support?

**Comment by tobbez** [comment]
Yes.

I plan on adding support once Deluge 2 is more widely accepted by trackers.

**Comment by brandond** [comment]
I'm using it, glad to test whenever you get around to it. I do have to fake an older clientid to get it to work on some trackers though...

**Comment by zimmertr** [comment]
Hi, it's whitelisted now on PTP and BTN. Would love for this to be available for v2 as well.

**Comment by tobbez** [comment]
Note that you may need to update your dashboards as the libtorrent metrics (`deluge_libtorrent_*`) have changed names.
