### ISSUE TITLE
[Enhancement] Add torrent states as labels for the `deluge_torrents` metric. 

### ISSUE THREAD

**Issue by Jafner** [tobbez/deluge_exporter#20]
I use multiple instances of Deluge for multiple trackers, so I have multiple exporters. I can easily separate metrics by exporter by labeling incoming metrics during scrape. 
I want to create a Grafana panel to monitor all torrents broken down by both tracker and state. 
I can't seem to figure out how to group these metrics by both tracker and state, since state is a query, not a label.

Would appreciate either the enhancement described in the title, or some assistance figuring out how to work this solution.

**Comment by tobbez** [comment]
It's not entirely clear what you're trying to achieve. Could you elaborate on what the end result you want would look like?
